template_url/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#for template tagging in html
app_name= 'basic_app'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^register/$', views.register, name='register'),
]

template_url/template_url/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from basic_app import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
]
"""
hey
"""

template_url/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User)

    portfolio_site = models.URLField(blank=True)
    profile_pic =models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

template_url/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password= forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields =('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields= ('portfolio_site','profile_pic')

template_url/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':' Fucking Bitch', 'number': '1'}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/rel_url.html')

template_url/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="nav navbar-nav">
                <li >
                    <a class="navbar-brand" href="{% url 'index'%}">DJANGO</a>
                </li>
                <li><a class="navbar-link" href="{% url 'admin:index'%}">ADMIN</a>&nbsp;</li>
                <li><a class="navbar-link" href="{% url 'basic_app:register'%}">REGISTER</a></li>
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

template_url/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
    {% block body_block %}
    <h1>Welcome to HomePage</h1>
    <h1> {{ text | upper }}</h1>
    <h1> {{ number }}</h1>
    {% endblock %}

template_url/templates/basic_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

template_url/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
    {% block body_block %}

    <h1>Welcome to other page</h1>
    <h2>Example of Template Inheritance</h2>

    {% endblock %}

template_url/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for Registering!</h1>
    {%else%}
    <h1>Register here !</h1>
    <h2>Fill in this form:</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" value="Register">
    </form>
    {% endif %}
</div>


{% endblock %}

template_url/templates/basic_app/rel_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>rel url</title>
</head>
<body>
<h1> Welcome to relative url templates</h1>
<h2>hiiii</h2>
<a href="{% url 'basic_app:other' %}">Other Page</a>
<a href="{% url 'admin:index' %}">Admin Page</a>
</body>
</html>